name: Deploy everything to dev
on: workflow_dispatch
jobs:
    deploy:
      name: Deploy
      environment: dev
      runs-on: ubuntu-latest
      steps:
        - name: Deploy DB wathcer
          uses: yc-actions/yc-sls-function@v2
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            folder-id: ${{ secrets.YC_OS_FOLDER_ID }}
            function-name: 'k8s-db-watcher4testing'
            runtime: 'python311'
            memory: '128Mb'
            execution-timeout: '600s'
            entrypoint: 'cloud_functions.db_watcher_function'
            environment: | 
              CONTOUR=${{ vars.CONTOUR }}
            secrets:
              SECRET=${{ secrets.YC_OS_SECRET_ID }}/${{ secrets.YC_OS_SECRET_VERSION }}/${{ vars.SECRET_KEY }}
            service-account: ${{ secrets.YC_OS_K8S_DEPLOYER_SA_ID }}
            network-id: ${{ secrets.YC_OS_NETWORK_ID }}
            include: | 
              requirements.txt
              ./src
              cloud_functions.py
            exclude: | 
              **/*.pyc